### ISSUE TITLE
Add icons 

### ISSUE THREAD

**Issue by ghadeerda** [itmo-wad/Ur-opinion#18]
Add icons and social logos on our website with [Font Awesome](https://fontawesome.com/) or any other useful one.

**Comment by Pablinjt** [comment]
We update the app using the code
@app.route('/favicon.ico')
def favicon():
    return send_from_directory("static","favicon.ico",mimetype="images/favicon.ico")

**Comment by Pablinjt** [comment]
and define
from flask import send_from_directory

**Comment by Pablinjt** [comment]
add icon file in the folder /static/

**Comment by ghadeerda** [comment]
@Pablinjt we already did this step, Pablo.

We need to choose icons to use in HTML files as symbols.
