### ISSUE TITLE
Choose a good database engine

### ISSUE THREAD

**Issue by Pablinjt** [itmo-wad/Ur-opinion#6]
Mongo
Postgres
Mysql

**Comment by Pablinjt** [comment]
after the analysis of the project, the MongoDB database engine was chosen.

**Comment by Pablinjt** [comment]
I have done insert tests from a python application and it is displayed that the data was entered correctly.
in my app just need to change this "client = MongoClient('localhost')"
to this
"client = MongoClient('mongodb+srv://user:password@cluster0-rkjna.gcp.mongodb.net/test?authSource=admin&replicaSet=Cluster0-shard-0&readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=true')"

**Comment by ghadeerda** [comment]
@Pablinjt Please take a look at the [wiki](https://github.com/itmo-wad/Ur-opinion/wiki/Database-description).

We can use mLab which is integrated with Heroku so it will be easier to deploy our website on Heroku.
