### ISSUE TITLE
Choose Google Material Design Components library

### ISSUE THREAD

**Issue by alekla** [itmo-wad/Ur-opinion#7]

**Comment by ghadeerda** [comment]
@alekla  can you please describe this issue?
What do you mean by google material ?

**Comment by alekla** [comment]
The design you showed is based on Google's visual components, so I thought we would use their components in the design.

**Comment by alekla** [comment]
If not, we can discuss or close issue.

**Comment by ghadeerda** [comment]
Understood, I just got an example from the internet, 
Yes, we can close because of no knowledge about these components.
